#!/bin/bash

# MySQL 替代安装方案：使用官方安装包
# 适用于网络受限环境

set -e

echo "📦 MySQL 替代安装方案"
echo ""
echo "由于网络限制，无法通过 Homebrew 安装 MySQL"
echo "请使用以下方式之一："
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "方案 1：下载 MySQL 官方安装包（推荐）"
echo ""
echo "1. 访问 MySQL 官方下载页面："
echo "   https://dev.mysql.com/downloads/mysql/"
echo ""
echo "2. 选择 macOS 版本，下载 .dmg 安装包"
echo ""
echo "3. 安装后，创建数据库和用户："
echo "   mysql -u root -p <<EOF"
echo "   CREATE DATABASE IF NOT EXISTS task_manager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "   CREATE USER IF NOT EXISTS 'task_user'@'localhost' IDENTIFIED BY 'task_password';"
echo "   GRANT ALL PRIVILEGES ON task_manager.* TO 'task_user'@'localhost';"
echo "   FLUSH PRIVILEGES;"
echo "   EOF"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "方案 2：使用 MariaDB（MySQL 兼容）"
echo ""
echo "MariaDB 是 MySQL 的开源分支，完全兼容 MySQL"
echo ""
echo "1. 访问 MariaDB 下载页面："
echo "   https://mariadb.org/download/"
echo ""
echo "2. 选择 macOS 版本下载安装"
echo ""
echo "3. 使用相同的数据库配置命令（与 MySQL 相同）"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "方案 3：配置 Homebrew 代理（如果有公司代理）"
echo ""
echo "如果你有 HTTP/HTTPS 代理，可以配置："
echo "   export http_proxy=http://proxy.example.com:8080"
echo "   export https_proxy=http://proxy.example.com:8080"
echo "   brew install mysql"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "安装完成后，请运行以下命令验证："
echo "   mysql --version"
echo "   mysql -u root -p -e 'SELECT 1;'"
echo ""
echo "然后运行 ./start.sh 启动项目"
